defaultSemverRangePrefix: ""

nodeLinker: pnp

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  rollup-plugin-ts@*:
    dependencies:
      "@babel/plugin-proposal-async-generator-functions": "*"
      "@babel/plugin-proposal-json-strings": "*"
      "@babel/plugin-proposal-object-rest-spread": "*"
      "@babel/plugin-proposal-optional-catch-binding": "*"
      "@babel/plugin-proposal-unicode-property-regex": "*"
      "@babel/plugin-syntax-dynamic-import": "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.4.cjs
